### ISSUE TITLE
hsla saturation and lightness 

### ISSUE THREAD

**Issue by RoyBraggBroadridge** [rbtech/gulp-css-purge#1]
when hsla() or hsl() is used if the saturation and/or lightness has a value of 0% the output css removes value. 
hsla(0, 0%, 60%, 0.6) outputs to hsla(0,, 60%, 0.6)
hsl(123, 10%, 0%) outputs to hsl(123,10%,,)

**Comment by AndrewEQ** [comment]
Hey @RoyBraggBroadridge, thanks for the feedback, will check it out and get back to ya.

**Comment by AndrewEQ** [comment]
Cool, found and fixed the issue: https://github.com/rbtech/css-purge/commit/a1f19d4564b423a8b2a513f4adf2610fc0f8fa4d#diff-e8acc63b1e238f3255c900eed37254b8
